"""YOLO dataset export (Ultralytics layout) with rotation augmentation.

Output::

    <export>/
        data.yaml
        images/train/*.jpg   images/val/*.jpg
        labels/train/*.txt   labels/val/*.txt

Split, static ROIs and augmentation are handled by ``export_common`` so YOLO and
COCO exports stay consistent. ``fmt`` selects detection (bbox) or segmentation
(polygon) labels.
"""
from __future__ import annotations

import shutil
from pathlib import Path
from typing import Optional

import numpy as np

from . import export_common as ec


def _bbox_from_points(pts: np.ndarray, w: int, h: int) -> tuple[float, float, float, float]:
    xs = np.clip(pts[:, 0], 0, w - 1)
    ys = np.clip(pts[:, 1], 0, h - 1)
    return float(xs.min()), float(ys.min()), float(xs.max()), float(ys.max())


def _label_line(ann: dict, pts: np.ndarray, w: int, h: int, fmt: str,
                id_map: dict) -> Optional[str]:
    cid = id_map.get(ann.get("class_id"))
    if cid is None:
        return None
    x0, y0, x1, y1 = _bbox_from_points(pts, w, h)
    if x1 - x0 < 1 or y1 - y0 < 1:
        return None
    if fmt == "segment" and ann.get("polygon") and len(ann["polygon"]) >= 3:
        coords = []
        for px, py in pts:
            coords.append(f"{min(max(px, 0), w - 1) / w:.6f}")
            coords.append(f"{min(max(py, 0), h - 1) / h:.6f}")
        return f"{cid} " + " ".join(coords)
    cx, cy = ((x0 + x1) / 2.0) / w, ((y0 + y1) / 2.0) / h
    bw, bh = (x1 - x0) / w, (y1 - y0) / h
    return f"{cid} {cx:.6f} {cy:.6f} {bw:.6f} {bh:.6f}"


def export_project(data: dict, out_dir: Path, *,
                   fmt: str = "detect", val_split: float = 0.1,
                   augment: bool = False, angles: Optional[list[float]] = None,
                   include_suggested: bool = False, seed: int = 42) -> dict:
    out_dir = Path(out_dir)
    classes, id_map = ec.class_id_map(data)
    if out_dir.exists():
        shutil.rmtree(out_dir)
    for split in ("train", "val"):
        (out_dir / "images" / split).mkdir(parents=True, exist_ok=True)
        (out_dir / "labels" / split).mkdir(parents=True, exist_ok=True)

    counts = {"train": 0, "val": 0, "instances": 0, "augmented": 0}
    for s in ec.iter_samples(data, val_split=val_split, augment=augment, angles=angles,
                             include_suggested=include_suggested, seed=seed):
        dst_img = out_dir / "images" / s.split / f"{s.stem}{s.ext}"
        if not s.write_image(dst_img):
            continue
        lines = []
        for ann, pts in zip(s.anns, s.pts_list):
            line = _label_line(ann, pts, s.width, s.height, fmt, id_map)
            if line:
                lines.append(line)
        (out_dir / "labels" / s.split / f"{s.stem}.txt").write_text(
            "\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")
        counts[s.split] += 1
        counts["instances"] += len(lines)
        if s.is_aug:
            counts["augmented"] += 1

    _write_data_yaml(out_dir, classes, fmt)
    counts["format"] = fmt
    counts["classes"] = len(classes)
    return counts


def _write_data_yaml(out_dir: Path, classes: list[dict], fmt: str) -> None:
    lines = [
        f"# Generated by QuickLabel — task: {'segmentation' if fmt == 'segment' else 'detection'}",
        f"path: {out_dir.resolve().as_posix()}",
        "train: images/train",
        "val: images/val",
        "",
        f"nc: {len(classes)}",
        "names:",
    ]
    for i, c in enumerate(classes):
        lines.append(f"  {i}: {c['name']}")
    (out_dir / "data.yaml").write_text("\n".join(lines) + "\n", encoding="utf-8")
